apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mycar-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mycar
  template:
    metadata:
      labels:
        app: mycar
    spec:
      containers:
      - name: mycar
        image: sanjoy-testdockerrepo.jfrog.io/mycar:0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe: 
          httpGet:
             path: /
             port: 8080
             initialDelaySeconds: 5
             periodSeconds: 5
             successThreshold: 1
      imagePullSecrets:
      - name: dockerregcred
        
